name: xview3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.0
  - attrs=20.3.0
  - bokeh=2.3.3
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.5
  - cfitsio=3.470
  - cftime=1.4.1
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - cryptography=3.4.6
  - curl=7.75.0
  - cycler=0.10.0
  - cython=0.29.23
  - cytoolz=0.11.0
  - dask=2021.7.0
  - dask-core=2021.7.0
  - distributed=2021.7.0
  - expat=2.2.10
  - fiona=1.8.18
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2021.7.0
  - gdal=3.2.1
  - geopandas=0.9.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - haversine=2.3.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=68.1
  - idna=2.10
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.15
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.75.0
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgdal=3.2.1
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - locket=0.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.2
  - msgpack-python=1.0.2
  - munch=2.5.0
  - ncurses=6.2
  - netcdf4=1.5.6
  - numpy=1.20.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.2.3
  - partd=1.2.0
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.0.1
  - pixman=0.40.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=13.1
  - proj=7.2.0
  - psutil=5.8.0
  - pthread-stubs=0.4
  - pycocotools=2.0.2
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.0.1
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - rasterio=1.2.1
  - readline=8.0
  - requests=2.25.1
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.35.2
  - tblib=1.7.0
  - threadpoolctl=2.2.0
  - tiledb=2.2.7
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - typing_extensions=3.10.0.0
  - tzcode=2021a
  - tzdata=2021a
  - urllib3=1.26.4
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - async-timeout==3.0.1
    - blessings==1.7
    - cachetools==4.2.2
    - colorama==0.4.4
    - colorful==0.5.4
    - filelock==3.0.12
    - geojson==2.5.0
    - geomet==0.3.0
    - google-api-core==1.31.0
    - google-auth==1.32.1
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - grpcio==1.38.1
    - hiredis==2.0.0
    - html2text==2020.1.16
    - jsonschema==3.2.0
    - multidict==5.1.0
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - prometheus-client==0.11.0
    - protobuf==3.17.3
    - py-spy==0.3.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pyrsistent==0.18.0
    - ray==1.4.1
    - redis==3.5.3
    - rsa==4.7.2
    - sentinelsat==0.14
    - torch==1.8.1
    - torchvision==0.9.1
    - tqdm==4.59.0
    - yarl==1.6.3
